// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	model "github.com/JesusG2000/hexsatisfaction/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Purchase is an autogenerated mock type for the Purchase type
type Purchase struct {
	mock.Mock
}

// Create provides a mock function with given fields: request
func (_m *Purchase) Create(request model.CreatePurchaseRequest) (int, error) {
	ret := _m.Called(request)

	var r0 int
	if rf, ok := ret.Get(0).(func(model.CreatePurchaseRequest) int); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.CreatePurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: request
func (_m *Purchase) Delete(request model.DeletePurchaseRequest) (int, error) {
	ret := _m.Called(request)

	var r0 int
	if rf, ok := ret.Get(0).(func(model.DeletePurchaseRequest) int); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.DeletePurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAfterDate provides a mock function with given fields: request
func (_m *Purchase) FindAfterDate(request model.AfterDatePurchaseRequest) ([]model.Purchase, error) {
	ret := _m.Called(request)

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func(model.AfterDatePurchaseRequest) []model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.AfterDatePurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *Purchase) FindAll() ([]model.Purchase, error) {
	ret := _m.Called()

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func() []model.Purchase); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByUserID provides a mock function with given fields: request
func (_m *Purchase) FindAllByUserID(request model.UserIDPurchaseRequest) ([]model.Purchase, error) {
	ret := _m.Called(request)

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func(model.UserIDPurchaseRequest) []model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.UserIDPurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBeforeDate provides a mock function with given fields: request
func (_m *Purchase) FindBeforeDate(request model.BeforeDatePurchaseRequest) ([]model.Purchase, error) {
	ret := _m.Called(request)

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func(model.BeforeDatePurchaseRequest) []model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.BeforeDatePurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByFileID provides a mock function with given fields: request
func (_m *Purchase) FindByFileID(request model.FileIDPurchaseRequest) ([]model.Purchase, error) {
	ret := _m.Called(request)

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func(model.FileIDPurchaseRequest) []model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.FileIDPurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: request
func (_m *Purchase) FindByID(request model.IDPurchaseRequest) (*model.Purchase, error) {
	ret := _m.Called(request)

	var r0 *model.Purchase
	if rf, ok := ret.Get(0).(func(model.IDPurchaseRequest) *model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.IDPurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPeriod provides a mock function with given fields: request
func (_m *Purchase) FindByPeriod(request model.PeriodPurchaseRequest) ([]model.Purchase, error) {
	ret := _m.Called(request)

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func(model.PeriodPurchaseRequest) []model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.PeriodPurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserIDAfterDate provides a mock function with given fields: request
func (_m *Purchase) FindByUserIDAfterDate(request model.UserIDAfterDatePurchaseRequest) ([]model.Purchase, error) {
	ret := _m.Called(request)

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func(model.UserIDAfterDatePurchaseRequest) []model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.UserIDAfterDatePurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserIDAndFileID provides a mock function with given fields: request
func (_m *Purchase) FindByUserIDAndFileID(request model.UserIDFileIDPurchaseRequest) ([]model.Purchase, error) {
	ret := _m.Called(request)

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func(model.UserIDFileIDPurchaseRequest) []model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.UserIDFileIDPurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserIDAndPeriod provides a mock function with given fields: request
func (_m *Purchase) FindByUserIDAndPeriod(request model.UserIDPeriodPurchaseRequest) ([]model.Purchase, error) {
	ret := _m.Called(request)

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func(model.UserIDPeriodPurchaseRequest) []model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.UserIDPeriodPurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserIDBeforeDate provides a mock function with given fields: request
func (_m *Purchase) FindByUserIDBeforeDate(request model.UserIDBeforeDatePurchaseRequest) ([]model.Purchase, error) {
	ret := _m.Called(request)

	var r0 []model.Purchase
	if rf, ok := ret.Get(0).(func(model.UserIDBeforeDatePurchaseRequest) []model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.UserIDBeforeDatePurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLast provides a mock function with given fields:
func (_m *Purchase) FindLast() (*model.Purchase, error) {
	ret := _m.Called()

	var r0 *model.Purchase
	if rf, ok := ret.Get(0).(func() *model.Purchase); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLastByUserID provides a mock function with given fields: request
func (_m *Purchase) FindLastByUserID(request model.UserIDPurchaseRequest) (*model.Purchase, error) {
	ret := _m.Called(request)

	var r0 *model.Purchase
	if rf, ok := ret.Get(0).(func(model.UserIDPurchaseRequest) *model.Purchase); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.UserIDPurchaseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
