// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	model "github.com/JesusG2000/hexsatisfaction/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Author is an autogenerated mock type for the Author type
type Author struct {
	mock.Mock
}

// Create provides a mock function with given fields: author
func (_m *Author) Create(author model.Author) (int, error) {
	ret := _m.Called(author)

	var r0 int
	if rf, ok := ret.Get(0).(func(model.Author) int); ok {
		r0 = rf(author)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Author) error); ok {
		r1 = rf(author)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Author) Delete(id int) (int, error) {
	ret := _m.Called(id)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *Author) FindAll() ([]model.Author, error) {
	ret := _m.Called()

	var r0 []model.Author
	if rf, ok := ret.Get(0).(func() []model.Author); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Author)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *Author) FindByID(id int) (*model.Author, error) {
	ret := _m.Called(id)

	var r0 *model.Author
	if rf, ok := ret.Get(0).(func(int) *model.Author); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Author)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: name
func (_m *Author) FindByName(name string) ([]model.Author, error) {
	ret := _m.Called(name)

	var r0 []model.Author
	if rf, ok := ret.Get(0).(func(string) []model.Author); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Author)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: id
func (_m *Author) FindByUserID(id int) (*model.Author, error) {
	ret := _m.Called(id)

	var r0 *model.Author
	if rf, ok := ret.Get(0).(func(int) *model.Author); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Author)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, author
func (_m *Author) Update(id int, author model.Author) (int, error) {
	ret := _m.Called(id, author)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, model.Author) int); ok {
		r0 = rf(id, author)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, model.Author) error); ok {
		r1 = rf(id, author)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
