# apiVersion: v1
# kind: Secret
# metadata:
#   name: hexsatisfaction-secret
# type: Opaque
# data:
#
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hexsatisfaction-config
data:
  PG_USER: hexsatisfaction_user
  PG_HOST: pgbouncer-service 
  PG_PORT: "5432"
  PG_DATABASE_NAME: slave0db
  PG_DATABASE_SSL_MODE: disable
  PG_DATABASE_DIALECT: postgres
  HTTP_HOST: "0.0.0.0"
  HTTP_PORT: "8080"
  HTTP_MAX_HEADER_BYTES: "1000"
  HTTP_READ_TIMEOUT: "10s"
  HTTP_WRITE_TIMEOUT: "10s"
  GRPC_HOST: "0.0.0.0"
  GRPC_PORT: "9090"
  JWT_SIGNING_KEY: c29tZV9qd3Q=
  PG_PASSWORD: "123456"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexsatisfaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexsatisfaction
  template:
    metadata:
      labels:
        app: hexsatisfaction
    spec:
      containers:
      - name: hexsatisfaction
        image: hexsatisfaction:1.0  # Replace with your Go application image
        envFrom:
        - configMapRef:
            name: hexsatisfaction-config
        # - secretRef:
        #     name: hexsatisfaction-secret
        ports:
        - containerPort: 8080  # HTTP port
        - containerPort: 9090  # gRPC port

---

apiVersion: v1
kind: Service
metadata:
  name: hexsatisfaction-http-service
spec:
  selector:
    app: hexsatisfaction
  ports:
    - protocol: TCP
      port: 7070  # External HTTP port
      targetPort: 8080  # Container HTTP port
  type: NodePort  # Expose as NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: hexsatisfaction-grpc-service
spec:
  selector:
    app: hexsatisfaction
  ports:
    - protocol: TCP
      port: 9090 # Cluster gRPC port
      targetPort: 9090  # Container gRPC port
  type: ClusterIP  # Expose as ClusterIP
