apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-job
spec:
  template:
    spec:
      containers:
      - name: cleanup-container
        image: busybox:1.0
        command: ["sh", "-c", "rm -rf /data"]
        volumeMounts:
        - name: postgres-data
          mountPath: /data
      volumes:
      - name: postgres-data
        hostPath:
          path: /tmp/hostpath-provisioner/default
      restartPolicy: Never

