apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexsatisfaction-postgres-master
spec:
  replicas: 1  # Single master instance
  selector:
    matchLabels:
      app: hexsatisfaction-postgres
      role: master  # Adding role label
  template:
    metadata:
      labels:
        app: hexsatisfaction-postgres
        role: master  # Adding role label
    spec:
      containers:
        - name: hexsatisfaction-postgres
          image: hexsatisfaction_postgres:1.0
          envFrom:
            - configMapRef:
                name: hexsatisfaction-postgres-config
            - secretRef:
                name: hexsatisfaction-postgres-secret
          ports:
            - containerPort: 5432
#psql -U hexsatisfaction_user -d hexsatisfaction -h hexsatisfaction-postgres-master-service
          # args: ['-h', 'localhost']
          volumeMounts:
            - name: pg-master-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-master-data 
          persistentVolumeClaim:
            claimName: hexsatisfaction-postgres-master-pvc 
---

apiVersion: v1
kind: Service
metadata:
  name: hexsatisfaction-postgres-master-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: hexsatisfaction-postgres
    role: master
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hexsatisfaction-postgres-master-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
